---
name: all_url_check

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '10 1 * * 1'

jobs:
  run_lychee:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: run lychee-action
        uses: lycheeverse/lychee-action@v1.5.1
        with:
          args: >
           --verbose
           --no-progress
           fail: true
...
